language: c

install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb &&
    sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman --noconfirm -S gba-dev
  - export DEVKITPRO=/opt/devkitpro
  - pip install --user cpp-coveralls

script:
  - make all examples
  - make check

after_success:
  - coveralls --include src --gcov-options '\-lp'
